module.exports = (sequelize,Sequelize)=>{
    const postCarModel = sequelize.define("postCarModel",{
        brand:{
            type:Sequelize.STRING,
            allowNull:false
        },
        year:{
            type:Sequelize.STRING,
            allowNull:false
        },
        fuel:{
            type:Sequelize.STRING,
            allowNull:false
        },
        transmission:{
            type:Sequelize.STRING,
            allowNull:false
        },
        kmdriven:{
            type:Sequelize.STRING,
            allowNull:false
        },
        noofowners:{
            type:Sequelize.STRING,
            allowNull:false
        },
        setaprice:{
            type:Sequelize.STRING,
            allowNull:false
        },
        adtitle:{
            type:Sequelize.STRING,
            allowNull:false
        },
        description:{
            type:Sequelize.STRING,
            allowNull:false
        },
        uploadphoto:{
            type:Sequelize.STRING,
            allowNull:false
        },
        state:{
            type:Sequelize.STRING,
            allowNull:false
        },
        city:{
            type:Sequelize.STRING,
            allowNull:false
        },
        neighbourhood:{
            type:Sequelize.STRING,
            allowNull:false
        },
        username:{
            type:Sequelize.STRING,
            allowNull:false
        },
        mobilenumber:{
            type:Sequelize.STRING,
            allowNull:false
        },
        email:{
            type:Sequelize.STRING,
            allowNull:false
        }
    })
    return postCarModel;
};